### ISSUE TITLE
version 2.0.0

### ISSUE THREAD

**Issue by stla** [stla/EllipticFunctions.jl#25]
@simonp0420 , @kagalenko-m-b 

I've just pushed a new version.

- better algorithm for the Jacobi theta functions
- Jacobi theta function with characteristics (it generalizes the four Jacobi theta functions)
- Based on the Jacobi theta function with characteristics, I redefined `_jtheta1dash0`, the derivative at `0` of the first Jacobi theta function

The third point has caused a problem: the test of the theta-S Neville function with extended precision has failed, because of a small imaginary part in the result while this result should be a real number. I added  `atol = 1e-15` in `@approx` in order that the test succeeded.

**Comment by stla** [comment]
Ah I've just had a thought. In the new `_jtheta1dash0`, there is a call to the generalized Jacobi theta function with a value `1/6`. Maybe we should promote the type of `1/6` to the extended precision.

**Comment by stla** [comment]
Yes, perfect. I've done `1/(6*one(tau))` and the test is successful!

**Comment by stla** [comment]
Would you know how to update the documentation? The page has been last deployed on July 2022. I don't remember how to trigger the update.

**Comment by simonp0420** [comment]
Looking at the log of one of your old successful documentation runs I see this:
![image](https://github.com/stla/EllipticFunctions.jl/assets/4294361/7d190dd4-577f-4bfb-b795-cff663f99def)

**Comment by stla** [comment]
Hmm... would you know where should I add this label?

**Comment by stla** [comment]
I see that in the YAML file:

```yaml
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    if: "contains( github.event.pull_request.labels.*.name, 'preview docs') || github.ref == 'refs/heads/master' || contains(github.ref, 'refs/tags/')"
    ......
```
So if I push on master, that should generate the doc?
